version: '3'

services:
  product-service:
    container_name: c_product-service
    build: ./product
    volumes:
      - ./product:/usr/src/app
    ports:
      - 6001:80

  website:
    image: php:apache
    container_name: c_website
    volumes:
      - ./website:/var/www/html
    ports:
      - 6002:80
    depends_on:
      - product-service
