version: '3'

services:
  product-service:
    container_name: c_03-python
    build: ./product
    volumes:
      - ./product:/usr/src/app
    restart: always
    ports:
      - 6003:80

  website:
    image: php:apache
    container_name: c_03-php-apache
    volumes:
      - ./website:/var/www/html
    restart: always
    ports:
      - 6004:80
    depends_on:
      - product-service
